version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    groups:
      nix-dependencies:
        patterns:
          - "*"
